spring.application.name=Caryanam_AutoHub

server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/Caryanam_AutoHub?createDatabaseIfNotExist=true&useSSL=true
spring.datasource.username=root
spring.datasource.password=swapnil@182


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect


spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

spring.jpa.hibernate.ddl-auto=update

spring.web.resources.static-locations=classpath:/static/,file:uploads/

file.upload-dir=uploads/dealers

# =========================================
# WhatsApp Cloud API Configuration
# =========================================


whatsapp.access-token=EAAOalWInKosBR54LOFAYrGYZCLDF73coZA56J66Bg48NKkIbyArQiOeFWlGHMv2ZAwHcZCMmDZCYVPIYGtLYujaeVYXKPkGRMrG6Ai8bSMB2kJO4k9jQvUj15DWCyCbp7L4njcR0ybFSg3NSBMZBZCxELHGSK9WYQfRuSymlSjBQ2ADbRaOL1EdA4ktCdZAyeEqzjXgfnT22ZBpAkRMMXR35vRgD7tNOZCfD16PKHuZASof2lNSUNhZCewT8HkT3F2OPktlCZBJzaRDE3jImNKSv5EZAlhCLeG
whatsapp.phone-number-id=1080921264657653
whatsapp.api-version=v25.0
whatsapp.template-name=lead_notification
whatsapp.language-code=en

whatsapp.base-url=https://graph.facebook.com
whatsapp.connect-timeout-ms=5000
whatsapp.read-timeout-ms=8000

# =========================================
# Async Thread Pool for WhatsApp Dispatch
# =========================================
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=15
spring.task.execution.pool.queue-capacity=200
spring.task.execution.thread-name-prefix=wa-async-

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=geetanjalikhaladkar86@gmail.com
spring.mail.password=qxlp yjyg smbg epxf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2


logging.level.org.springframework.web.socket=TRACE
logging.level.org.springframework.messaging=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.messaging.simp=TRACE

logging.level.org.springframework.messaging.handler=TRACE
logging.level.org.springframework.security=DEBUG